name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.x'

    - name: Docker setup buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Docker build and push
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker buildx build \
          --platform linux/amd64 \
          -t kimdongjae/gifted_dirac:${{ github.sha }} \
          ./solmoi-express \
          --push

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH Setup
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" | sed 's/\r$//' > ~/.ssh/solmoi-key.pem
        chmod 600 ~/.ssh/solmoi-key.pem
        ssh-keyscan -H ec2-13-209-16-83.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/solmoi-key.pem ubuntu@ec2-13-209-16-83.ap-northeast-2.compute.amazonaws.com "
        export GITHUB_SHA=${{ github.sha }} &&
        cd /home/ubuntu/Server &&
        echo \"MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}\" > .env &&
        echo \"MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}\" >> .env &&
        echo \"MYSQL_USER=${{ secrets.MYSQL_USER }}\" >> .env &&
        echo \"MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}\" >> .env &&
        echo \"MYSQL_HOST=db\" >> .env &&
        echo \"MYSQL_PORT=3306\" >> .env &&
        chmod 600 .env &&
        docker-compose down -v || true &&
        docker-compose pull &&
        docker-compose up -d
        "